apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-engine
  template:
    metadata:
      labels:
        app: dashboard-engine
    spec:
      containers:
      - name: dashboard-engine
        image: mahmut/analytics-engine:v1
        imagePullPolicy: Never
        command: ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
        ports:
        - containerPort: 8501
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
spec:
  selector:
    app: dashboard-engine
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamer-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer-engine
  template:
    metadata:
      labels:
        app: streamer-engine
    spec:
      containers:
      - name: streamer-engine
        image: mahmut/analytics-engine:v1
        imagePullPolicy: Never
        command: ["python", "streamer.py"]
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictor-engine
  template:
    metadata:
      labels:
        app: predictor-engine
    spec:
      containers:
      - name: predictor-engine
        image: mahmut/analytics-engine:v1
        imagePullPolicy: Never
        command: ["python", "prediction-engine/predictor.py"]
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluator-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluator-engine
  template:
    metadata:
      labels:
        app: evaluator-engine
    spec:
      containers:
      - name: evaluator-engine
        image: mahmut/analytics-engine:v1
        imagePullPolicy: Never
        command: ["python", "prediction-engine/evaluator.py"]
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"