---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector-engine
  template:
    metadata:
      labels:
        app: data-collector-engine
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z kafka-broker 9092; do echo "Waiting for Kafka..."; sleep 3; done;']
      containers:
        - name: data-collector
          image: quantstream/data-collector:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-broker:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-engine
  template:
    metadata:
      labels:
        app: aggregator-engine
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z kafka-broker 9092; do echo "Waiting for Kafka..."; sleep 3; done;']
      containers:
        - name: aggregator
          image: quantstream/analytics-engine:latest
          imagePullPolicy: Never
          command: ["python", "aggregator.py"]
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-broker:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictor-engine
  template:
    metadata:
      labels:
        app: predictor-engine
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z kafka-broker 9092; do echo "Waiting for Kafka..."; sleep 3; done;']
      containers:
        - name: predictor
          image: quantstream/analytics-engine:latest
          imagePullPolicy: Never
          command: ["python", "prediction-engine/predictor.py"]
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-broker:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-engine
  template:
    metadata:
      labels:
        app: dashboard-engine
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z kafka-broker 9092; do echo "Waiting for Kafka..."; sleep 3; done;']
      containers:
        - name: dashboard
          image: quantstream/analytics-engine:latest
          imagePullPolicy: Never
          command: ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
          ports:
            - containerPort: 8501
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-broker:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
spec:
  selector:
    app: dashboard-engine
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: ClusterIP
