apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector-engine
  template:
    metadata:
      labels:
        app: data-collector-engine
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox
        command: ['sh', '-c', 'until nc -z kafka-service 9092; do echo waiting for kafka; sleep 2; done;']
      containers:
      - name: data-collector
        image: mahmut/data-collector:v1
        imagePullPolicy: Never
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-engine
  template:
    metadata:
      labels:
        app: aggregator-engine
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox
        command: ['sh', '-c', 'until nc -z kafka-service 9092; do echo waiting for kafka; sleep 2; done;']
      containers:
      - name: aggregator
        image: mahmut/analytics-engine:v1
        imagePullPolicy: Never
        command: ["python", "aggregator.py"]
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictor-engine
  template:
    metadata:
      labels:
        app: predictor-engine
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox
        command: ['sh', '-c', 'until nc -z kafka-service 9092; do echo waiting for kafka; sleep 2; done;']
      containers:
      - name: predictor
        image: mahmut/analytics-engine:v1
        imagePullPolicy: Never
        command: ["python", "prediction-engine/predictor.py"]
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-engine
  template:
    metadata:
      labels:
        app: dashboard-engine
    spec:
      containers:
      - name: dashboard
        image: mahmut/analytics-engine:v1
        imagePullPolicy: Never
        command: ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
        ports:
        - containerPort: 8501
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
spec:
  type: NodePort
  selector:
    app: dashboard-engine
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30501
